### ISSUE TITLE
Possible issue causing extraneous API requests

### ISSUE THREAD

**Issue by Juicestus** [TexasTorque/Torque-Hours#10]
@0marA @humandavey

On [line 23 of src/pages/AddUser.jsx](https://github.com/TexasTorque/TorqueHours/blob/767d209180509cf464e72072fa030b1bffe5f9b4/src/pages/AddUser.jsx#L23C3-L23C3) the `useEffect` does not include a second parameter (the list of state objects to reference).

The lack of this second parameter causes the function to execute on every render cycle. The stack trace of this function shows that it calls the API. 

This *could* result in a bunch of extraneous API requests. Its worth checking to make sure its not.

I can't be certain because it depends on runtime state. I was just reading the code and noticed this mistake. Rarely do you want a `useEffect` with no second parameter. Only if you want an update loop in the app.

**Comment by humandavey** [comment]
That `useEffect` just checks to see if they are pressing enter and as such needs to be a sort of update function, so it would only cause API requests when someone presses enter and they have inputted a name to add. I believe the issue with the API requests is caused by having the firebase console open when we are actively developing which counts as a read every time a piece of data is loaded to be viewed as shown [here](https://stackoverflow.com/a/67968791).

**Comment by Juicestus** [comment]
👍
